// Generated by rong-typegen from the fs module's Rust source.
// Do not edit by hand — run `cargo run -p rong_typegen` to regenerate.

export interface FileOpenOptions {
  /** Open the file for reading. Defaults to true. */
  read?: boolean;
  /** Open the file for writing. Defaults to false. */
  write?: boolean;
  /** Append writes to the end of the file. */
  append?: boolean;
  /** Truncate the file to zero bytes when opening it for writing. */
  truncate?: boolean;
  /** Create the file when it does not exist. */
  create?: boolean;
  /** Create a new file and fail when it already exists. */
  createNew?: boolean;
  /** Unix file permissions mode. */
  mode?: number;
}

export interface FileSinkOptions {
  /** If true, open file in append mode. Default is truncate (overwrite). */
  append?: boolean;
  /** Unix file permissions mode. */
  mode?: number;
}

export interface MkdirOptions {
  /** Create missing parent directories. Defaults to false. */
  recursive?: boolean;
  /** Unix permissions mode for the created directory. */
  mode?: number;
}

export interface RemoveOptions {
  /** Recursively remove non-empty directories. Defaults to false. */
  recursive?: boolean;
}

/** Access and modification timestamps for `Rong.utime`. */
export interface UTimeOptions {
  /** Access time in Unix epoch milliseconds. Defaults to the current time. */
  accessed?: number;
  /** Modification time in Unix epoch milliseconds. Defaults to the current time. */
  modified?: number;
}

/** Seek origin constants exposed as `Rong.SeekMode`. */
export declare const SeekMode: {
  /** Seek from start of file (absolute position). */
  readonly Start: 0;
  /** Seek from current position (relative). */
  readonly Current: 1;
  /** Seek from end of file (usually a negative offset). */
  readonly End: 2;
};
export type SeekMode = (typeof SeekMode)[keyof typeof SeekMode];

/** One directory entry returned by `Rong.readDir`. */
export declare class DirEntry {
  private constructor();
  readonly name: string;
  readonly isFile: boolean;
  readonly isDirectory: boolean;
  readonly isSymlink: boolean;
}

/** Low-level random-access file handle returned by `RongFile.open`. */
export declare class FileHandle {
  private constructor();
  /** Read metadata for the open file. */
  stat(): Promise<FileInfo>;
  /** Read into an ArrayBuffer, returning null at end of file. */
  read(buffer: ArrayBuffer): Promise<number | null>;
  /** Write the complete ArrayBuffer at the current position. */
  write(buffer: ArrayBuffer): Promise<number>;
  /** Flush file contents and metadata to stable storage. */
  sync(): Promise<void>;
  /** Resize the file, defaulting to zero bytes. */
  truncate(len?: number): Promise<void>;
  /** Move the current file position and return the new offset. */
  seek(offset: number, whence?: SeekMode): Promise<number>;
  /** Close this handle. Further operations fail. */
  close(): Promise<void>;
  /** Readable byte stream backed by this handle. */
  readonly readable: ReadableStream<Uint8Array>;
  /** Writable byte stream backed by this handle. */
  readonly writable: WritableStream<Uint8Array>;
}

/** File or directory metadata returned by stat operations. */
export declare class FileInfo {
  private constructor();
  /** Whether this metadata describes a regular file. */
  readonly isFile: boolean;
  /** Whether this metadata describes a directory. */
  readonly isDirectory: boolean;
  /** Whether this metadata describes a symbolic link. */
  readonly isSymlink: boolean;
  /** Size in bytes. */
  readonly size: number;
  /** Last modification time in Unix epoch milliseconds, when available. */
  readonly modified: number | null;
  /** Last access time in Unix epoch milliseconds, when available. */
  readonly accessed: number | null;
  /** Creation time in Unix epoch milliseconds, when available. */
  readonly created: number | null;
  /** Unix permissions mode, or null on unsupported platforms. */
  readonly mode: number | null;
}

/** Incremental writer returned by `RongFile.writer`. */
export declare class FileSink {
  private constructor();
  /** Write data and return the number of bytes written. */
  write(data: string | ArrayBufferView | ArrayBuffer): Promise<number>;
  /** Flush buffered data to the file. */
  flush(): Promise<void>;
  /** Flush and close the writer. */
  end(): Promise<void>;
}

/** Lazy file reference created by `Rong.file(path)`. */
export declare class RongFile {
  private constructor();
  /** Original path supplied to `Rong.file`. */
  readonly name: string;
  /** Read the complete file as UTF-8 text. */
  text(): Promise<string>;
  /** Read and parse the complete file as JSON. */
  json(): Promise<any>;
  /** Read the complete file as bytes. */
  bytes(): Promise<Uint8Array>;
  /** Read the complete file as an ArrayBuffer. */
  arrayBuffer(): Promise<ArrayBuffer>;
  /** Stream the file contents in byte chunks. */
  stream(): ReadableStream<Uint8Array>;
  /** Test whether the path exists. */
  exists(): Promise<boolean>;
  /** Delete the referenced file. */
  delete(): Promise<void>;
  /** Read metadata while following symbolic links. */
  stat(): Promise<FileInfo>;
  /** Read metadata without following the final symbolic link. */
  lstat(): Promise<FileInfo>;
  /** Open a low-level random-access file handle. */
  open(options?: FileOpenOptions): Promise<FileHandle>;
  /** Open an incremental file writer. */
  writer(options?: FileSinkOptions): Promise<FileSink>;
}

declare global {
  interface RongNamespace {
    file(path: string): RongFile;
    /**
     * Universal write: Rong.write(dest, data) -> Promise<number>
     * dest: string path or RongFile
     * data: string, TypedArray, ArrayBuffer, or RongFile (copy)
     */
    write(dest: string | RongFile, data: string | ArrayBufferView | ArrayBuffer | RongFile): Promise<number>;
    mkdir(path: string, options?: MkdirOptions): Promise<void>;
    readDir(path: string): Promise<AsyncIterableIterator<DirEntry>>;
    remove(path: string, options?: RemoveOptions): Promise<void>;
    chdir(path: string): Promise<void>;
    /** Create a symbolic link */
    symlink(target: string, path: string): Promise<void>;
    /** Read the target of a symbolic link */
    readlink(path: string): Promise<string>;
    /** Change file permissions (Unix only) */
    chmod(path: string, mode: number): Promise<void>;
    /** Change file ownership (Unix only) */
    chown(path: string, uid: number, gid: number): Promise<void>;
    /** Change file access and modification times */
    utime(path: string, options: UTimeOptions): Promise<void>;
    /** Rename a file or directory */
    rename(oldPath: string, newPath: string): Promise<void>;
    /** Get the real path (canonical path) of a file */
    realPath(path: string): Promise<string>;
    readonly SeekMode: typeof SeekMode;
  }
}
