// Generated by rong-typegen from the fs module's Rust source.
// Do not edit by hand — run `cargo run -p rong_typegen` to regenerate.

export interface FileOpenOption {
  read?: boolean;
  write?: boolean;
  append?: boolean;
  truncate?: boolean;
  create?: boolean;
  createNew?: boolean;
  mode?: number;
}

export interface FileSinkOptions {
  /** If true, open file in append mode. Default is truncate (overwrite). */
  append?: boolean;
  /** Unix file permissions mode. */
  mode?: number;
}

export interface MkdirOptions {
  recursive?: boolean;
  mode?: number;
}

export interface RemoveOptions {
  recursive: boolean;
}

/** Options for utime function */
export interface UTimeOptions {
  accessed?: number;
  modified?: number;
}

/** Seek origin constants exposed as `Rong.SeekMode`. */
export declare const SeekMode: {
  /** Seek from start of file (absolute position). */
  readonly Start: 0;
  /** Seek from current position (relative). */
  readonly Current: 1;
  /** Seek from end of file (usually a negative offset). */
  readonly End: 2;
};
export type SeekMode = (typeof SeekMode)[keyof typeof SeekMode];

export declare class DirEntry {
  private constructor();
  readonly name: string;
  readonly isFile: boolean;
  readonly isDirectory: boolean;
  readonly isSymlink: boolean;
}

export declare class FileHandle {
  private constructor();
  stat(): Promise<FileInfo>;
  read(buffer: ArrayBuffer): Promise<number | null>;
  write(buffer: ArrayBuffer): Promise<number>;
  sync(): Promise<void>;
  truncate(len?: number): Promise<void>;
  seek(offset: number, whence?: SeekMode): Promise<number>;
  close(): Promise<void>;
  readonly readable: ReadableStream<Uint8Array>;
  readonly writable: WritableStream<Uint8Array>;
}

export declare class FileInfo {
  private constructor();
  readonly isFile: boolean;
  readonly isDirectory: boolean;
  readonly isSymlink: boolean;
  readonly size: number;
  readonly modified: number | null;
  readonly accessed: number | null;
  readonly created: number | null;
  readonly mode: number | null;
}

export declare class FileSink {
  private constructor();
  write(data: string | ArrayBufferView | ArrayBuffer): Promise<number>;
  flush(): Promise<void>;
  end(): Promise<void>;
}

export declare class RongFile {
  private constructor();
  readonly name: string;
  text(): Promise<string>;
  json(): Promise<any>;
  bytes(): Promise<Uint8Array>;
  arrayBuffer(): Promise<ArrayBuffer>;
  stream(): ReadableStream<Uint8Array>;
  exists(): Promise<boolean>;
  delete(): Promise<void>;
  stat(): Promise<FileInfo>;
  lstat(): Promise<FileInfo>;
  open(option?: FileOpenOption): Promise<FileHandle>;
  writer(option?: FileSinkOptions): Promise<FileSink>;
}

