// Generated by rong-typegen from the s3 module's Rust source.
// Do not edit by hand — run `cargo run -p rong_typegen` to regenerate.

/** Options for constructing or overriding an S3 client. */
export interface S3ClientOptions {
  /** AWS access key ID. */
  accessKeyId?: string;
  /** AWS secret access key. */
  secretAccessKey?: string;
  /** AWS session token (STS). */
  sessionToken?: string;
  /** AWS region. */
  region?: string;
  /** Custom endpoint URL (for S3-compatible services). */
  endpoint?: string;
  /** Bucket name. */
  bucket?: string;
  /** Default ACL for uploads (e.g. "public-read"). */
  acl?: string;
  /** Use virtual-hosted-style URLs instead of path-style. */
  virtualHostedStyle?: boolean;
}

/** Single object entry in a list result. */
export interface S3ListEntry {
  /** Object key. */
  key: string;
  /** Object size in bytes. */
  size: number;
  /** Last modified timestamp (ISO 8601 string). */
  lastModified: string;
  /** ETag of the object. */
  etag?: string;
}

/** Options for list operations. */
export interface S3ListOptions {
  /** Filter objects by key prefix. */
  prefix?: string;
  /** Maximum number of keys to return. */
  maxKeys?: number;
  /** Start listing after this key (for pagination). */
  startAfter?: string;
}

/** Result of a list operation. */
export interface S3ListResult {
  /** List of matching objects. */
  contents: S3ListEntry[];
  /** Whether there are more results (use `startAfter` to paginate). */
  isTruncated: boolean;
}

/** Options for presigning URLs. */
export interface S3PresignOptions {
  /** Expiration in seconds. */
  expiresIn?: number;
  /** HTTP method. */
  method?: "GET" | "PUT" | "DELETE";
}

/** Object metadata returned by `stat()`. */
export interface S3StatResult {
  /** ETag of the object. */
  etag?: string;
  /** Last modified timestamp (ISO 8601 string). */
  lastModified?: string;
  /** Object size in bytes. */
  size: number;
  /** Content-Type of the object. */
  type?: string;
}

/** Options for write operations. */
export interface S3WriteOptions {
  /** Content-Type header. */
  type?: string;
}

export declare class S3Client {
  constructor(options?: S3ClientOptions);
  /** Lazy file reference — no network request. */
  file(path: string, options?: S3ClientOptions): S3File;
  write(path: string, data: string | ArrayBuffer | Uint8Array, options?: S3WriteOptions & S3ClientOptions): Promise<number>;
  delete(path: string): Promise<void>;
  unlink(path: string): Promise<void>;
  exists(path: string): Promise<boolean>;
  size(path: string): Promise<number>;
  stat(path: string): Promise<S3StatResult>;
  presign(path: string, options?: S3PresignOptions & S3ClientOptions): Promise<string>;
  list(options?: S3ListOptions & S3ClientOptions): Promise<S3ListResult>;
}

export declare class S3File {
  private constructor();
  readonly name: string;
  /** S3 objects don't have synchronous size — use stat() instead. */
  readonly size: number;
  text(): Promise<string>;
  json(): Promise<any>;
  bytes(): Promise<ArrayBuffer>;
  arrayBuffer(): Promise<ArrayBuffer>;
  /** Write data to this S3 object. */
  write(data: string | ArrayBuffer | Uint8Array, options?: S3WriteOptions): Promise<number>;
  delete(): Promise<void>;
  unlink(): Promise<void>;
  exists(): Promise<boolean>;
  stat(): Promise<S3StatResult>;
  /** Generate a presigned URL (async in rust-s3). */
  presign(options?: S3PresignOptions): Promise<string>;
  slice(start: number, end?: number): S3File;
}

