// Generated by rong-typegen from the sqlite module's Rust source.
// Do not edit by hand — run `cargo run -p rong_typegen` to regenerate.

// Irreducible TS for the sqlite module: parameter unions with no backing Rust
// struct. Authored here (their origin), not mirrored from Rust.

/** A value bindable as a SQLite statement parameter. */
export type SQLiteParam = null | boolean | number | bigint | string | ArrayBuffer | Uint8Array;
export type SQLiteParams = SQLiteParam[];

/** Result of a write (INSERT/UPDATE/DELETE). */
export interface RunResult {
  /** Number of rows changed. */
  changes: number;
  /** Row id of the last inserted row; large values come back as `bigint`. */
  lastInsertRowid: number | bigint;
}

export declare class SQLite {
  constructor(filename?: string);
  /**
   * Execute a SQL string that may contain multiple statements.
   * Use for DDL / schema setup.
   */
  exec(sql: string): void;
  /**
   * Execute a single statement with optional parameters.
   * Returns `{ changes, lastInsertRowid }`.
   */
  run(sql: string, params?: SQLiteParams): RunResult;
  /** Execute a query and return all matching rows as an array of objects. */
  query(sql: string, params?: SQLiteParams): Record<string, any>[];
  /** Create a prepared statement for repeated execution. */
  prepare(sql: string): Statement;
  /** Run a function inside a transaction. Commits on success, rolls back on error. */
  transaction(callback: () => void): void;
  readonly filename: string;
  /** Whether the database is currently inside a transaction. */
  readonly inTransaction: boolean;
  close(): void;
}

export declare class Statement {
  private constructor();
  /** Execute the statement. Returns `{ changes, lastInsertRowid }`. */
  run(params?: SQLiteParams): RunResult;
  /** Execute and return all rows as array of objects. */
  all(params?: SQLiteParams): Record<string, any>[];
  /** Execute and return the first row, or null if no match. */
  get(params?: SQLiteParams): Record<string, any> | null;
  /** Execute and return all rows as arrays of values (column-order tuples). */
  values(params?: SQLiteParams): any[][];
  /** Mark the statement as finalized. Further calls will throw. */
  finalize(): void;
  /** The SQL text of this statement. */
  readonly sql: string;
}

