// Generated by rong-typegen from the storage module's Rust source.
// Do not edit by hand — run `cargo run -p rong_typegen` to regenerate.

export interface StorageInfo {
  currentSize: number;
  limitSize: number;
  keyCount: number;
}

export interface StorageOptionsInput {
  maxKeySize?: number;
  maxValueSize?: number;
  maxDataSize?: number;
}

export declare class Storage {
  constructor(path: string, options?: StorageOptionsInput);
  /** Set a key-value pair in storage */
  set(key: string, value: any): Promise<void>;
  /** Get a value from storage */
  get(key: string): Promise<any>;
  /** Delete a key from storage */
  delete(key: string): Promise<void>;
  /** Clear all data from storage */
  clear(): Promise<void>;
  /** Storage list function that returns an iterator */
  list(prefix?: string): Promise<IterableIterator<string>>;
  /** Storage info function */
  info(): Promise<StorageInfo>;
}

