// Generated by rong-typegen from the storage module's Rust source.
// Do not edit by hand — run `cargo run -p rong_typegen` to regenerate.

/** Current storage usage and configured limits. */
export interface StorageInfo {
  /** Current serialized user-data size in bytes. */
  currentSize: number;
  /** Configured user-data size limit in bytes. */
  limitSize: number;
  /** Number of stored keys. */
  keyCount: number;
}

/** Optional storage limits in bytes. */
export interface StorageOptionsInput {
  /** Maximum UTF-8 key size. */
  maxKeySize?: number;
  /** Maximum serialized value size. */
  maxValueSize?: number;
  /** Maximum total user-data size. */
  maxDataSize?: number;
}

/** Persistent key/value storage backed by a local database. */
export declare class Storage {
  constructor(path: string, options?: StorageOptionsInput);
  /** Set a key-value pair in storage */
  set(key: string, value: any): Promise<void>;
  /** Get a value from storage */
  get(key: string): Promise<any>;
  /** Delete a key from storage */
  delete(key: string): Promise<void>;
  /** Clear all data from storage */
  clear(): Promise<void>;
  /** Storage list function that returns an iterator */
  list(prefix?: string): Promise<IterableIterator<string>>;
  /** Storage info function */
  info(): Promise<StorageInfo>;
}
