// Generated by rong-typegen from the url module's Rust source.
// Do not edit by hand — run `cargo run -p rong_typegen` to regenerate.

export declare class URL {
  constructor(url: string, base?: string);
  hash: string;
  host: string;
  hostname: string;
  href: string;
  readonly origin: string;
  password: string;
  pathname: string;
  port: string;
  protocol: string;
  search: string;
  username: string;
  readonly searchParams: URLSearchParams;
  toString(): string;
  toJSON(): string;
}

export declare class URLSearchParams {
  constructor(init?: any);
  append(name: string, value: string): void;
  delete(name: string): void;
  get(name: string): string | null;
  getAll(name: string): string[];
  has(name: string): boolean;
  set(name: string, value: string): void;
  sort(): void;
  readonly size: number;
  entries(): Array<[string, string]>;
  keys(): string[];
  values(): string[];
  forEach(callback: (value: string, key: string) => void, thisArg?: any): void;
  toString(): string;
}
