// Generated by rong-typegen from the url module's Rust source.
// Do not edit by hand — run `cargo run -p rong_typegen` to regenerate.

/** WHATWG-style URL parser and mutable URL object. */
export declare class URL {
  /** Parse an absolute URL or resolve a relative URL against a base. */
  constructor(url: string, base?: string);
  /** Fragment identifier including the leading `#`. */
  hash: string;
  /** Hostname and port. */
  host: string;
  /** Hostname without the port. */
  hostname: string;
  /** Serialized URL. */
  href: string;
  /** Origin consisting of scheme and host. */
  readonly origin: string;
  /** Password component. */
  password: string;
  /** Path component. */
  pathname: string;
  /** Port as a string. */
  port: string;
  /** Protocol including the trailing `:`. */
  protocol: string;
  /** Query string including the leading `?`. */
  search: string;
  /** Username component. */
  username: string;
  /** Live search-parameter view backed by this URL. */
  readonly searchParams: URLSearchParams;
  /** Serialize this URL. */
  toString(): string;
  /** Serialize this URL for JSON conversion. */
  toJSON(): string;
}

/** Ordered query-string parameters following the URLSearchParams API. */
export declare class URLSearchParams {
  /** Construct from a query string, pair array, or string record. */
  constructor(init?: string | Array<[string, string]> | Record<string, string>);
  /** Append a value without removing existing values. */
  append(name: string, value: string): void;
  /** Delete every value associated with a name. */
  delete(name: string): void;
  /** Return the first value for a name, or null. */
  get(name: string): string | null;
  /** Return every value associated with a name. */
  getAll(name: string): string[];
  /** Test whether a name is present. */
  has(name: string): boolean;
  /** Replace existing values for a name. */
  set(name: string, value: string): void;
  /** Sort parameters by name. */
  sort(): void;
  /** Number of stored name/value pairs. */
  readonly size: number;
  /** Return all name/value pairs. */
  entries(): Array<[string, string]>;
  /** Return all parameter names. */
  keys(): string[];
  /** Return all parameter values. */
  values(): string[];
  /** Invoke a callback for each parameter. */
  forEach(callback: (value: string, key: string) => void, thisArg?: any): void;
  /** Serialize as a query string without a leading `?`. */
  toString(): string;
}
