//! Generate TypeScript definitions for RongJS modules from their Rust source.
//!
//! Default mode follows `packages/rong_types/typegen.json`, which explicitly
//! decides whether each module is canonical (`src/`) or a drift reference
//! (`generated/`). Single-crate mode writes to an explicit `--out` directory.

use rong_typedef::model::{Item, ModuleTypeDef};
use rong_typedef::{extract_const_enum, extract_impl, extract_struct, render_module};
use serde::Deserialize;
use std::collections::{BTreeMap, BTreeSet, HashSet};
use std::path::{Path, PathBuf};
use std::process::ExitCode;

const GEN_MARKER: &str = "// Generated by rong-typegen";
const POLICY_FILE: &str = "typegen.json";

fn main() -> ExitCode {
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("error: {error}");
            ExitCode::FAILURE
        }
    }
}

fn run() -> Result<(), String> {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let check = args.iter().any(|a| a == "--check");
    let explicit_out = flag(&args, "--out").map(PathBuf::from);
    let explicit_name = flag(&args, "--name");
    let explicit_src = positional(&args).map(PathBuf::from);

    if explicit_src.is_none() && (explicit_out.is_some() || explicit_name.is_some()) {
        return Err("--out/--name require an explicit SRC_DIR".to_string());
    }

    if let Some(src) = explicit_src {
        let out =
            explicit_out.ok_or_else(|| "single-crate mode requires `--out DIR`".to_string())?;
        let name = explicit_name.unwrap_or_else(|| dir_name(&src));
        let module = module_from_crate(&CrateSrc { name, src })?;
        if module.items.is_empty() {
            return Err("no JS-facing types found in the configured source graph".to_string());
        }
        let prelude_dir = out.parent().map(|p| p.join("preludes"));
        let file = out.join(format!("{}.ts", module.module));
        return emit_one(&module, &file, prelude_dir.as_deref(), check);
    }

    run_repository_mode(check)
}

fn run_repository_mode(check: bool) -> Result<(), String> {
    let pkg = repo_root().join("packages/rong_types");
    let policy = load_policy(&pkg.join(POLICY_FILE))?;
    let crates = rong_module_crates()?;
    let mut discovered = BTreeMap::new();

    for source in crates {
        let module = module_from_crate(&source)?;
        if !module.items.is_empty() {
            discovered.insert(module.module.clone(), module);
        }
    }

    let unconfigured: Vec<_> = discovered
        .keys()
        .filter(|name| !policy.modules.contains_key(*name))
        .cloned()
        .collect();
    if !unconfigured.is_empty() {
        return Err(format!(
            "JS-facing modules missing from {POLICY_FILE}: {}",
            unconfigured.join(", ")
        ));
    }

    let mut expected = BTreeSet::new();
    let mut outputs = Vec::new();
    for (name, mode) in &policy.modules {
        let module = discovered.get(name).ok_or_else(|| {
            format!(
                "module `{name}` is configured in {POLICY_FILE} but has no extractable JS-facing types"
            )
        })?;
        let file = match mode {
            OutputMode::Canonical => pkg.join("src").join(format!("{name}.ts")),
            OutputMode::Reference => pkg.join("generated").join(format!("{name}.ts")),
        };
        expected.insert(file.clone());
        outputs.push((module, file));
    }

    let managed = managed_outputs(&pkg)?;
    let unexpected: Vec<PathBuf> = managed.difference(&expected).cloned().collect();
    if check && !unexpected.is_empty() {
        return Err(format_paths(
            "unexpected managed type outputs (remove them or add them to typegen.json)",
            &unexpected,
        ));
    }
    if !check {
        for path in &unexpected {
            if path.starts_with(pkg.join("generated")) {
                std::fs::remove_file(path)
                    .map_err(|e| format!("remove stale {}: {e}", path.display()))?;
                println!("removed stale {}", path.display());
            } else {
                return Err(format!(
                    "{} is marked as generated but is not canonical in {POLICY_FILE}; remove or reclassify it explicitly",
                    path.display()
                ));
            }
        }
    }

    let prelude_dir = pkg.join("preludes");
    let mut stale = Vec::new();
    for (module, file) in outputs {
        let rendered = rendered_module(module, Some(&prelude_dir))?;
        if check {
            if std::fs::read_to_string(&file).unwrap_or_default() != rendered {
                stale.push(file);
            }
        } else {
            write_output(&file, &rendered)?;
        }
    }

    if !stale.is_empty() {
        return Err(format_paths(
            "generated types are out of date; run `cargo run -p rong_typegen`",
            &stale,
        ));
    }
    if check {
        println!("types are up to date ({} modules).", expected.len());
    }
    Ok(())
}

fn emit_one(
    module: &ModuleTypeDef,
    file: &Path,
    prelude_dir: Option<&Path>,
    check: bool,
) -> Result<(), String> {
    let rendered = rendered_module(module, prelude_dir)?;
    if check {
        if std::fs::read_to_string(file).unwrap_or_default() != rendered {
            return Err(format!(
                "{} is out of date; rerun without --check",
                file.display()
            ));
        }
        println!("types are up to date (1 module).");
    } else {
        write_output(file, &rendered)?;
    }
    Ok(())
}

fn rendered_module(module: &ModuleTypeDef, prelude_dir: Option<&Path>) -> Result<String, String> {
    let prelude_path = prelude_dir.map(|dir| dir.join(format!("{}.ts", module.module)));
    let prelude = match prelude_path {
        Some(path) if path.exists() => {
            std::fs::read_to_string(&path)
                .map_err(|e| format!("read prelude {}: {e}", path.display()))?
                .trim_end()
                .to_string()
                + "\n\n"
        }
        _ => String::new(),
    };
    let rendered = header(&module.module) + &prelude + &render_module(module);
    Ok(format!("{}\n", rendered.trim_end()))
}

fn write_output(file: &Path, rendered: &str) -> Result<(), String> {
    if let Some(parent) = file.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| format!("create dir {}: {e}", parent.display()))?;
    }
    std::fs::write(file, rendered).map_err(|e| format!("write {}: {e}", file.display()))?;
    println!("generated {}", file.display());
    Ok(())
}

#[derive(Debug, Deserialize)]
struct TypegenPolicy {
    modules: BTreeMap<String, OutputMode>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "lowercase")]
enum OutputMode {
    Canonical,
    Reference,
}

fn load_policy(path: &Path) -> Result<TypegenPolicy, String> {
    let source = std::fs::read_to_string(path)
        .map_err(|e| format!("read policy {}: {e}", path.display()))?;
    let policy: TypegenPolicy = serde_json::from_str(&source)
        .map_err(|e| format!("parse policy {}: {e}", path.display()))?;
    if policy.modules.is_empty() {
        return Err(format!("policy {} has no modules", path.display()));
    }
    Ok(policy)
}

fn managed_outputs(pkg: &Path) -> Result<BTreeSet<PathBuf>, String> {
    let mut paths = BTreeSet::new();
    let generated = pkg.join("generated");
    if generated.exists() {
        for entry in std::fs::read_dir(&generated)
            .map_err(|e| format!("read dir {}: {e}", generated.display()))?
        {
            let path = entry
                .map_err(|e| format!("read dir entry {}: {e}", generated.display()))?
                .path();
            if path.extension().and_then(|e| e.to_str()) == Some("ts") {
                paths.insert(path);
            }
        }
    }

    let src = pkg.join("src");
    for entry in std::fs::read_dir(&src).map_err(|e| format!("read dir {}: {e}", src.display()))? {
        let path = entry
            .map_err(|e| format!("read dir entry {}: {e}", src.display()))?
            .path();
        if path.extension().and_then(|e| e.to_str()) == Some("ts") {
            let text = std::fs::read_to_string(&path)
                .map_err(|e| format!("read {}: {e}", path.display()))?;
            if text.starts_with(GEN_MARKER) {
                paths.insert(path);
            }
        }
    }
    Ok(paths)
}

struct CrateSrc {
    name: String,
    src: PathBuf,
}

fn rong_module_crates() -> Result<Vec<CrateSrc>, String> {
    let modules = repo_root().join("modules");
    let entries = std::fs::read_dir(&modules)
        .map_err(|e| format!("read modules dir {}: {e}", modules.display()))?;
    let mut out = Vec::new();
    for entry in entries {
        let dir = entry
            .map_err(|e| format!("read modules entry: {e}"))?
            .path();
        let src = dir.join("src");
        if src.is_dir()
            && let Some(name) = dir.file_name().and_then(|n| n.to_str())
            && let Some(name) = name.strip_prefix("rong_")
        {
            out.push(CrateSrc {
                name: name.to_string(),
                src,
            });
        }
    }
    out.sort_by(|a, b| a.name.cmp(&b.name));
    Ok(out)
}

fn module_from_crate(c: &CrateSrc) -> Result<ModuleTypeDef, String> {
    let root = crate_root_file(&c.src)?;
    let module_dir = root
        .parent()
        .ok_or_else(|| format!("source root has no parent: {}", root.display()))?
        .to_path_buf();
    let mut items = Vec::new();
    let mut visited = HashSet::new();
    visit_file(&root, &module_dir, &mut visited, &mut items)?;
    items.sort_by_key(sort_key);
    Ok(ModuleTypeDef {
        module: c.name.clone(),
        items,
    })
}

fn crate_root_file(src: &Path) -> Result<PathBuf, String> {
    if src.is_file() {
        return Ok(src.to_path_buf());
    }
    for name in ["lib.rs", "main.rs", "mod.rs"] {
        let candidate = src.join(name);
        if candidate.is_file() {
            return Ok(candidate);
        }
    }
    Err(format!(
        "no lib.rs, main.rs, or mod.rs under {}",
        src.display()
    ))
}

fn visit_file(
    file: &Path,
    module_dir: &Path,
    visited: &mut HashSet<PathBuf>,
    out: &mut Vec<Item>,
) -> Result<(), String> {
    let file = file
        .canonicalize()
        .map_err(|e| format!("resolve {}: {e}", file.display()))?;
    if !visited.insert(file.clone()) {
        return Ok(());
    }
    let text = std::fs::read_to_string(&file)
        .map_err(|e| format!("read Rust source {}: {e}", file.display()))?;
    let ast =
        syn::parse_file(&text).map_err(|e| format!("parse Rust source {}: {e}", file.display()))?;
    collect_items(&ast.items, &file, module_dir, visited, out)
}

fn collect_items(
    items: &[syn::Item],
    current_file: &Path,
    module_dir: &Path,
    visited: &mut HashSet<PathBuf>,
    out: &mut Vec<Item>,
) -> Result<(), String> {
    for item in items {
        match item {
            syn::Item::Impl(i) if !cfg_test(&i.attrs) => {
                if let Some(desc) = extract_impl(i) {
                    out.push(desc);
                } else if has_attr(&i.attrs, "js_class") {
                    return Err(format!(
                        "could not extract #[js_class] impl in {}",
                        current_file.display()
                    ));
                } else if rong_typedef::has_orphan_js_methods(i) {
                    return Err(format!(
                        "#[js_method] appears in an impl without #[js_class] in {}",
                        current_file.display()
                    ));
                }
            }
            syn::Item::Struct(s) if !cfg_test(&s.attrs) => {
                if let Some(desc) = extract_struct(s) {
                    out.push(desc);
                }
            }
            syn::Item::Enum(e) if !cfg_test(&e.attrs) => {
                if let Some(desc) = extract_const_enum(e) {
                    if let Item::ConstEnum(def) = &desc
                        && def.variants.len() != e.variants.len()
                    {
                        return Err(format!(
                            "could not extract every #[js_const_enum] variant in {}",
                            current_file.display()
                        ));
                    }
                    out.push(desc);
                }
            }
            syn::Item::Mod(m) if !cfg_test(&m.attrs) => {
                let child_dir = module_dir.join(m.ident.to_string());
                if let Some((_, inner)) = &m.content {
                    collect_items(inner, current_file, &child_dir, visited, out)?;
                } else {
                    let path = resolve_module_file(m, current_file, module_dir)?;
                    let next_dir = if path.file_name().and_then(|n| n.to_str()) == Some("mod.rs") {
                        path.parent().unwrap_or(module_dir).to_path_buf()
                    } else {
                        path.with_extension("")
                    };
                    visit_file(&path, &next_dir, visited, out)?;
                }
            }
            syn::Item::Macro(m) if macro_may_hide_js_api(m) => {
                return Err(format!(
                    "macro item in {} contains JS binding annotations; typegen cannot safely expand it",
                    current_file.display()
                ));
            }
            _ => {}
        }
    }
    Ok(())
}

fn resolve_module_file(
    module: &syn::ItemMod,
    current_file: &Path,
    module_dir: &Path,
) -> Result<PathBuf, String> {
    if let Some(relative) = path_override(&module.attrs) {
        let base = current_file.parent().unwrap_or(module_dir);
        let path = base.join(relative);
        if path.is_file() {
            return Ok(path);
        }
        return Err(format!(
            "#[path] module file does not exist: {}",
            path.display()
        ));
    }

    let name = module.ident.to_string();
    let candidates = [
        module_dir.join(format!("{name}.rs")),
        module_dir.join(&name).join("mod.rs"),
    ];
    candidates
        .into_iter()
        .find(|path| path.is_file())
        .ok_or_else(|| {
            format!(
                "cannot resolve module `{name}` declared in {}",
                current_file.display()
            )
        })
}

fn path_override(attrs: &[syn::Attribute]) -> Option<PathBuf> {
    attrs.iter().find_map(|attr| {
        if !attr.path().is_ident("path") {
            return None;
        }
        let syn::Meta::NameValue(value) = &attr.meta else {
            return None;
        };
        let syn::Expr::Lit(expr) = &value.value else {
            return None;
        };
        let syn::Lit::Str(path) = &expr.lit else {
            return None;
        };
        Some(PathBuf::from(path.value()))
    })
}

fn cfg_test(attrs: &[syn::Attribute]) -> bool {
    attrs.iter().any(|attr| {
        if !attr.path().is_ident("cfg") {
            return false;
        }
        let syn::Meta::List(list) = &attr.meta else {
            return false;
        };
        list.parse_args::<syn::Meta>()
            .is_ok_and(|meta| matches!(meta, syn::Meta::Path(path) if path.is_ident("test")))
    })
}

fn has_attr(attrs: &[syn::Attribute], name: &str) -> bool {
    attrs.iter().any(|attr| {
        attr.path()
            .segments
            .last()
            .is_some_and(|segment| segment.ident == name)
    })
}

fn macro_may_hide_js_api(item: &syn::ItemMacro) -> bool {
    let tokens = item.mac.tokens.to_string();
    [
        "js_class",
        "js_method",
        "js_const_enum",
        "FromJSObj",
        "IntoJSObj",
    ]
    .iter()
    .any(|needle| tokens.contains(needle))
}

fn sort_key(item: &Item) -> String {
    match item {
        Item::TypeAlias(a) => format!("0:{}", a.name),
        Item::Interface(i) => format!("1:{}", i.name),
        Item::ConstEnum(e) => format!("2:{}", e.name),
        Item::Class(c) => format!("3:{}", c.name),
    }
}

fn header(module: &str) -> String {
    format!(
        "// Generated by rong-typegen from the {module} module's Rust source.\n\
         // Do not edit by hand — run `cargo run -p rong_typegen` to regenerate.\n\n"
    )
}

fn format_paths(message: &str, paths: &[PathBuf]) -> String {
    let paths = paths
        .iter()
        .map(|path| format!("\n  {}", path.display()))
        .collect::<String>();
    format!("{message}:{paths}")
}

fn flag(args: &[String], name: &str) -> Option<String> {
    let idx = args.iter().position(|a| a == name)?;
    args.get(idx + 1).cloned()
}

fn positional(args: &[String]) -> Option<String> {
    let mut i = 0;
    while i < args.len() {
        let a = &args[i];
        if a == "--check" {
            i += 1;
        } else if a == "--out" || a == "--name" {
            i += 2;
        } else {
            return Some(a.clone());
        }
    }
    None
}

fn dir_name(p: &Path) -> String {
    let base = if p.file_name().and_then(|n| n.to_str()) == Some("src") {
        p.parent().unwrap_or(p)
    } else {
        p
    };
    base.file_name()
        .and_then(|n| n.to_str())
        .map(|n| n.strip_prefix("rong_").unwrap_or(n).to_string())
        .unwrap_or_else(|| "module".to_string())
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("repo root")
        .to_path_buf()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn args(a: &[&str]) -> Vec<String> {
        a.iter().map(|s| s.to_string()).collect()
    }

    #[test]
    fn flag_reads_value_after_name() {
        let a = args(&["--out", "dir", "--name", "x"]);
        assert_eq!(flag(&a, "--out").as_deref(), Some("dir"));
        assert_eq!(flag(&a, "--name").as_deref(), Some("x"));
        assert_eq!(flag(&a, "--missing"), None);
    }

    #[test]
    fn positional_skips_flags_and_their_values() {
        assert_eq!(
            positional(&args(&["--check", "--out", "gen", "src/path"])).as_deref(),
            Some("src/path")
        );
        assert_eq!(positional(&args(&["--check"])), None);
    }

    #[test]
    fn dir_name_strips_src_and_rong_prefix() {
        assert_eq!(dir_name(Path::new("/a/lingxia-logic/src")), "lingxia-logic");
        assert_eq!(dir_name(Path::new("/a/rong_sqlite")), "sqlite");
    }

    #[test]
    fn cfg_test_is_excluded_but_other_cfgs_are_target_agnostic() {
        let test: syn::ItemMod = syn::parse_quote! { #[cfg(test)] mod tests {} };
        let unix: syn::ItemMod = syn::parse_quote! { #[cfg(unix)] mod unix {} };
        assert!(cfg_test(&test.attrs));
        assert!(!cfg_test(&unix.attrs));
    }

    #[test]
    fn module_graph_ignores_unreferenced_files_and_test_modules() {
        let root = temp_dir("module-graph");
        let src = root.join("src");
        std::fs::create_dir_all(&src).unwrap();
        std::fs::write(
            src.join("lib.rs"),
            "mod live;\n#[cfg(test)] mod tests { #[derive(FromJSObj)] struct TestOnly { value: String } }\n",
        )
        .unwrap();
        std::fs::write(
            src.join("live.rs"),
            "#[derive(FromJSObj)] struct Live { value: String }\n",
        )
        .unwrap();
        std::fs::write(
            src.join("dead.rs"),
            "#[derive(FromJSObj)] struct Dead { value: String }\n",
        )
        .unwrap();

        let module = module_from_crate(&CrateSrc {
            name: "fixture".into(),
            src,
        })
        .unwrap();
        let names: Vec<_> = module
            .items
            .iter()
            .map(|item| match item {
                Item::Interface(value) => value.name.as_str(),
                _ => "unexpected",
            })
            .collect();
        assert_eq!(names, ["Live"]);
        std::fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn managed_outputs_are_explicitly_enumerated() {
        let root = temp_dir("managed-outputs");
        let src = root.join("src");
        let generated = root.join("generated");
        std::fs::create_dir_all(&src).unwrap();
        std::fs::create_dir_all(&generated).unwrap();
        std::fs::write(src.join("canonical.ts"), format!("{GEN_MARKER}\n")).unwrap();
        std::fs::write(src.join("hand.ts"), "export interface Hand {}\n").unwrap();
        std::fs::write(generated.join("reference.ts"), format!("{GEN_MARKER}\n")).unwrap();

        let managed = managed_outputs(&root).unwrap();
        assert!(managed.contains(&src.join("canonical.ts")));
        assert!(managed.contains(&generated.join("reference.ts")));
        assert!(!managed.contains(&src.join("hand.ts")));
        std::fs::remove_dir_all(root).unwrap();
    }

    fn temp_dir(label: &str) -> PathBuf {
        let nonce = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        std::env::temp_dir().join(format!(
            "rong-typegen-{label}-{}-{nonce}",
            std::process::id()
        ))
    }
}
