//! Generate TypeScript definitions for RongJS modules from their Rust source.
//!
//! Default mode follows `packages/rong_types/typegen.json`, which explicitly
//! decides whether each module is generated canonically (`src/`) or remains a
//! deliberately curated TypeScript surface. Single-crate mode writes to an
//! explicit `--out` directory.

use rong_typedef::model::{
    Item, ModuleTypeDef, NamespaceDef, NamespaceMember, NamespaceValueDef, TypeAliasDef,
};
use rong_typedef::{
    JsApiEntry, JsApiInput, extract_function, extract_impl, extract_numeric_enum, extract_struct,
    extract_union, render_module,
};
use serde::Deserialize;
use std::collections::{BTreeMap, BTreeSet, HashSet};
use std::path::{Path, PathBuf};
use std::process::ExitCode;

const GEN_MARKER: &str = "// Generated by rong-typegen";
const POLICY_FILE: &str = "typegen.json";

fn main() -> ExitCode {
    match run() {
        Ok(()) => ExitCode::SUCCESS,
        Err(error) => {
            eprintln!("error: {error}");
            ExitCode::FAILURE
        }
    }
}

fn run() -> Result<(), String> {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let args = CliArgs::parse(&args)?;
    if let Some(config) = args.config {
        return run_downstream_config(&config, args.check);
    }
    if let Some(src) = args.src {
        let out = args.out.expect("validated by CliArgs::parse");
        let name = args.name.unwrap_or_else(|| dir_name(&src));
        let module = module_from_crate(&CrateSrc { name, src })?;
        if module.items.is_empty() {
            return Err("no JS-facing types found in the configured source graph".to_string());
        }
        let file = out.join(format!("{}.ts", module.module));
        return emit_one(&module, &file, args.check);
    }

    run_repository_mode(args.check)
}

#[derive(Debug, Default, PartialEq, Eq)]
struct CliArgs {
    check: bool,
    config: Option<PathBuf>,
    out: Option<PathBuf>,
    name: Option<String>,
    src: Option<PathBuf>,
}

impl CliArgs {
    fn parse(args: &[String]) -> Result<Self, String> {
        let mut parsed = Self::default();
        let mut index = 0;
        while index < args.len() {
            match args[index].as_str() {
                "--check" => {
                    if parsed.check {
                        return Err("duplicate --check".to_string());
                    }
                    parsed.check = true;
                    index += 1;
                }
                "--config" | "--out" | "--name" => {
                    let flag = args[index].as_str();
                    let value = args
                        .get(index + 1)
                        .filter(|value| !value.starts_with('-'))
                        .ok_or_else(|| format!("{flag} requires a value"))?
                        .clone();
                    match flag {
                        "--config" if parsed.config.is_none() => parsed.config = Some(value.into()),
                        "--out" if parsed.out.is_none() => parsed.out = Some(value.into()),
                        "--name" if parsed.name.is_none() => parsed.name = Some(value),
                        _ => return Err(format!("duplicate {flag}")),
                    }
                    index += 2;
                }
                value if value.starts_with('-') => {
                    return Err(format!("unknown option: {value}"));
                }
                value => {
                    if parsed.src.is_some() {
                        return Err(format!("unexpected positional argument: {value}"));
                    }
                    parsed.src = Some(value.into());
                    index += 1;
                }
            }
        }

        if parsed.config.is_some()
            && (parsed.src.is_some() || parsed.out.is_some() || parsed.name.is_some())
        {
            return Err("--config cannot be combined with SRC_DIR, --out, or --name".to_string());
        }
        if parsed.src.is_none() && (parsed.out.is_some() || parsed.name.is_some()) {
            return Err("--out/--name require an explicit SRC_DIR".to_string());
        }
        if parsed.src.is_some() && parsed.out.is_none() {
            return Err("single-crate mode requires `--out DIR`".to_string());
        }
        Ok(parsed)
    }
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct DownstreamConfig {
    source: PathBuf,
    name: String,
    out: PathBuf,
    #[serde(default)]
    preludes: Vec<PathBuf>,
    #[serde(default)]
    global_objects: BTreeMap<String, String>,
    #[serde(default)]
    profiles: BTreeMap<RuntimeProfile, PathBuf>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Deserialize)]
#[serde(rename_all = "kebab-case")]
enum RuntimeProfile {
    LogicWeb,
}

fn run_downstream_config(path: &Path, check: bool) -> Result<(), String> {
    let path = path
        .canonicalize()
        .map_err(|error| format!("resolve config {}: {error}", path.display()))?;
    let base = path
        .parent()
        .ok_or_else(|| format!("config has no parent directory: {}", path.display()))?;
    let source = std::fs::read_to_string(&path)
        .map_err(|error| format!("read config {}: {error}", path.display()))?;
    let config: DownstreamConfig = serde_json::from_str(&source)
        .map_err(|error| format!("parse config {}: {error}", path.display()))?;

    let module = module_from_crate(&CrateSrc {
        name: config.name,
        src: base.join(config.source),
    })?;
    if module.items.is_empty() {
        return Err("no JS-facing types found in the configured source graph".to_string());
    }
    let mut rendered = header(&module.module);
    for prelude in config.preludes {
        let prelude = base.join(prelude);
        rendered.push_str(
            std::fs::read_to_string(&prelude)
                .map_err(|error| format!("read prelude {}: {error}", prelude.display()))?
                .trim_end(),
        );
        rendered.push_str("\n\n");
    }
    rendered.push_str(&render_module(&module));
    if !config.global_objects.is_empty() {
        rendered.push_str("declare global {\n");
        for (value, interface) in config.global_objects {
            if !ts_identifier(&value) || !ts_identifier(&interface) {
                return Err(format!(
                    "global object mapping requires TypeScript identifiers: `{value}` -> `{interface}`"
                ));
            }
            rendered.push_str(&format!("  const {value}: {interface};\n"));
        }
        rendered.push_str("}\n\n");
    }
    rendered.push_str("export {};\n");
    emit_content(
        &base.join(config.out),
        &format!("{}\n", rendered.trim_end()),
        check,
    )?;

    for (profile, output) in config.profiles {
        emit_content(&base.join(output), runtime_profile(profile), check)?;
    }
    Ok(())
}

fn ts_identifier(value: &str) -> bool {
    let mut chars = value.chars();
    chars
        .next()
        .is_some_and(|c| c == '_' || c == '$' || c.is_ascii_alphabetic())
        && chars.all(|c| c == '_' || c == '$' || c.is_ascii_alphanumeric())
}

fn runtime_profile(profile: RuntimeProfile) -> &'static str {
    match profile {
        RuntimeProfile::LogicWeb => rong_typedef::LOGIC_WEB_PROFILE,
    }
}

fn emit_content(file: &Path, rendered: &str, check: bool) -> Result<(), String> {
    if check {
        if std::fs::read_to_string(file).unwrap_or_default() != rendered {
            return Err(format!("{} is out of date", file.display()));
        }
        println!("{} is up to date.", file.display());
        Ok(())
    } else {
        write_output(file, rendered)
    }
}

fn run_repository_mode(check: bool) -> Result<(), String> {
    let pkg = repo_root().join("packages/rong_types");
    let policy = load_policy(&pkg.join(POLICY_FILE))?;
    let crates = rong_module_crates()?;
    let mut discovered = BTreeMap::new();

    for source in crates {
        let module = module_from_crate(&source)?;
        if !module.items.is_empty() {
            discovered.insert(module.module.clone(), module);
        }
    }

    let unconfigured: Vec<_> = discovered
        .keys()
        .filter(|name| !policy.modules.contains_key(*name))
        .cloned()
        .collect();
    if !unconfigured.is_empty() {
        return Err(format!(
            "JS-facing modules missing from {POLICY_FILE}: {}",
            unconfigured.join(", ")
        ));
    }

    let mut expected = BTreeSet::new();
    let mut outputs = Vec::new();
    for (name, mode) in &policy.modules {
        let module = discovered.get(name).ok_or_else(|| {
            format!(
                "module `{name}` is configured in {POLICY_FILE} but has no extractable JS-facing types"
            )
        })?;
        let OutputMode::Canonical = mode else {
            continue;
        };
        let file = pkg.join("src").join(format!("{name}.ts"));
        expected.insert(file.clone());
        outputs.push((module, file));
    }

    let managed = managed_outputs(&pkg)?;
    let unexpected: Vec<PathBuf> = managed.difference(&expected).cloned().collect();
    if check && !unexpected.is_empty() {
        return Err(format_paths(
            "unexpected managed type outputs (remove them or add them to typegen.json)",
            &unexpected,
        ));
    }
    if !check {
        for path in &unexpected {
            if path.starts_with(pkg.join("generated")) {
                std::fs::remove_file(path)
                    .map_err(|e| format!("remove stale {}: {e}", path.display()))?;
                println!("removed stale {}", path.display());
            } else {
                return Err(format!(
                    "{} is marked as generated but is not canonical in {POLICY_FILE}; remove or reclassify it explicitly",
                    path.display()
                ));
            }
        }
    }

    let mut stale = Vec::new();
    for (module, file) in outputs {
        let rendered = rendered_module(module);
        if check {
            if std::fs::read_to_string(&file).unwrap_or_default() != rendered {
                stale.push(file);
            }
        } else {
            write_output(&file, &rendered)?;
        }
    }

    if !stale.is_empty() {
        return Err(format_paths(
            "generated types are out of date; run `cargo run -p rong_typegen`",
            &stale,
        ));
    }
    if check {
        println!("types are up to date ({} modules).", expected.len());
    }
    Ok(())
}

fn emit_one(module: &ModuleTypeDef, file: &Path, check: bool) -> Result<(), String> {
    let rendered = rendered_module(module);
    if check {
        if std::fs::read_to_string(file).unwrap_or_default() != rendered {
            return Err(format!(
                "{} is out of date; rerun without --check",
                file.display()
            ));
        }
        println!("types are up to date (1 module).");
    } else {
        write_output(file, &rendered)?;
    }
    Ok(())
}

fn rendered_module(module: &ModuleTypeDef) -> String {
    let rendered = header(&module.module) + &render_module(module);
    format!("{}\n", rendered.trim_end())
}

fn write_output(file: &Path, rendered: &str) -> Result<(), String> {
    if let Some(parent) = file.parent() {
        std::fs::create_dir_all(parent)
            .map_err(|e| format!("create dir {}: {e}", parent.display()))?;
    }
    std::fs::write(file, rendered).map_err(|e| format!("write {}: {e}", file.display()))?;
    println!("generated {}", file.display());
    Ok(())
}

#[derive(Debug, Deserialize)]
#[serde(deny_unknown_fields)]
struct TypegenPolicy {
    modules: BTreeMap<String, OutputMode>,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "lowercase")]
enum OutputMode {
    Canonical,
    Curated,
}

fn load_policy(path: &Path) -> Result<TypegenPolicy, String> {
    let source = std::fs::read_to_string(path)
        .map_err(|e| format!("read policy {}: {e}", path.display()))?;
    let policy: TypegenPolicy = serde_json::from_str(&source)
        .map_err(|e| format!("parse policy {}: {e}", path.display()))?;
    if policy.modules.is_empty() {
        return Err(format!("policy {} has no modules", path.display()));
    }
    Ok(policy)
}

fn managed_outputs(pkg: &Path) -> Result<BTreeSet<PathBuf>, String> {
    let mut paths = BTreeSet::new();
    let generated = pkg.join("generated");
    if generated.exists() {
        for entry in std::fs::read_dir(&generated)
            .map_err(|e| format!("read dir {}: {e}", generated.display()))?
        {
            let path = entry
                .map_err(|e| format!("read dir entry {}: {e}", generated.display()))?
                .path();
            if path.extension().and_then(|e| e.to_str()) == Some("ts") {
                paths.insert(path);
            }
        }
    }

    let src = pkg.join("src");
    for entry in std::fs::read_dir(&src).map_err(|e| format!("read dir {}: {e}", src.display()))? {
        let path = entry
            .map_err(|e| format!("read dir entry {}: {e}", src.display()))?
            .path();
        if path.extension().and_then(|e| e.to_str()) == Some("ts") {
            let text = std::fs::read_to_string(&path)
                .map_err(|e| format!("read {}: {e}", path.display()))?;
            if text.starts_with(GEN_MARKER) {
                paths.insert(path);
            }
        }
    }
    Ok(paths)
}

struct CrateSrc {
    name: String,
    src: PathBuf,
}

fn rong_module_crates() -> Result<Vec<CrateSrc>, String> {
    let modules = repo_root().join("modules");
    let entries = std::fs::read_dir(&modules)
        .map_err(|e| format!("read modules dir {}: {e}", modules.display()))?;
    let mut out = Vec::new();
    for entry in entries {
        let dir = entry
            .map_err(|e| format!("read modules entry: {e}"))?
            .path();
        let src = dir.join("src");
        if src.is_dir()
            && let Some(name) = dir.file_name().and_then(|n| n.to_str())
            && let Some(name) = name.strip_prefix("rong_")
        {
            out.push(CrateSrc {
                name: name.to_string(),
                src,
            });
        }
    }
    out.sort_by(|a, b| a.name.cmp(&b.name));
    Ok(out)
}

fn module_from_crate(c: &CrateSrc) -> Result<ModuleTypeDef, String> {
    let root = crate_root_file(&c.src)?;
    let module_dir = root
        .parent()
        .ok_or_else(|| format!("source root has no parent: {}", root.display()))?
        .to_path_buf();
    let mut extraction = Extraction::default();
    let mut visited = HashSet::new();
    visit_file(&root, &module_dir, &[], &mut visited, &mut extraction)?;
    extraction.resolve_namespaces()?;
    validate_type_aliases(&extraction.items)?;
    extraction.items.sort_by_key(sort_key);
    Ok(ModuleTypeDef {
        module: c.name.clone(),
        items: extraction.items,
    })
}

fn validate_type_aliases(items: &[Item]) -> Result<(), String> {
    let mut declarations = BTreeMap::<&str, &'static str>::new();
    for item in items {
        let (name, kind) = match item {
            Item::TypeAlias(value) => (value.name.as_str(), "type alias"),
            Item::Interface(value) => (value.name.as_str(), "interface"),
            Item::NumericEnum(value) => (value.name.as_str(), "numeric enum"),
            Item::Class(value) => (value.name.as_str(), "class"),
            Item::Namespace(_) => continue,
        };
        if let Some(previous) = declarations.insert(name, kind)
            && (previous == "type alias" || kind == "type alias")
        {
            return Err(format!(
                "TypeScript type alias `{name}` conflicts with a generated {previous}"
            ));
        }
    }
    Ok(())
}

#[derive(Default)]
struct Extraction {
    items: Vec<Item>,
    functions: BTreeMap<String, Vec<syn::ItemFn>>,
    apis: Vec<(Vec<String>, JsApiInput)>,
}

impl Extraction {
    fn resolve_namespaces(&mut self) -> Result<(), String> {
        let mut namespaces: BTreeMap<String, Vec<NamespaceMember>> = BTreeMap::new();
        let mut exported_names = BTreeSet::new();
        for (module_path, api) in self.apis.drain(..) {
            let namespace_name = api.namespace.to_string();
            let members = namespaces.entry(namespace_name.clone()).or_default();
            for entry in api.entries {
                let entry = match entry {
                    JsApiEntry::TypeAlias(alias) => {
                        self.items.push(Item::TypeAlias(TypeAliasDef {
                            name: alias.name.to_string(),
                            ts_type: alias.ts_type.value(),
                            docs: alias.docs,
                        }));
                        continue;
                    }
                    entry => entry,
                };
                let export_name = match &entry {
                    JsApiEntry::Function(export) => export.name.value(),
                    JsApiEntry::Class(export) => export.name.value(),
                    JsApiEntry::Const(export) => export.name.value(),
                    JsApiEntry::TypeAlias(_) => unreachable!(),
                };
                if !exported_names.insert((namespace_name.clone(), export_name.clone())) {
                    return Err(format!(
                        "duplicate `{export_name}` registration in TypeScript interface `{namespace_name}`"
                    ));
                }
                match entry {
                    JsApiEntry::Function(export) => {
                        let key =
                            resolve_function_key(&self.functions, &module_path, &export.function)?;
                        let functions = self.functions.get(&key).ok_or_else(|| {
                            format!("registered namespace function `{key}` was not found")
                        })?;
                        let definitions: Vec<_> = functions
                            .iter()
                            .map(|function| {
                                extract_function(
                                    function,
                                    export.name.value(),
                                    export.ts_params.as_ref().map(|value| value.value()),
                                    export.ts_return.as_ref().map(|value| value.value()),
                                )
                            })
                            .collect();
                        if definitions
                            .windows(2)
                            .any(|pair| pair[0].sig != pair[1].sig)
                        {
                            return Err(format!(
                                "cfg variants of registered function `{key}` produce different TypeScript signatures"
                            ));
                        }
                        members.push(NamespaceMember::Function(
                            definitions.into_iter().next().ok_or_else(|| {
                                format!("registered namespace function `{key}` has no definition")
                            })?,
                        ));
                    }
                    JsApiEntry::Const(export) => {
                        members.push(NamespaceMember::Value(NamespaceValueDef {
                            name: export.name.value(),
                            ts_type: export.ts_type.value(),
                        }));
                    }
                    JsApiEntry::Class(export) => {
                        let class_name = export
                            .class
                            .segments
                            .last()
                            .expect("class path has a segment")
                            .ident
                            .to_string();
                        members.push(NamespaceMember::Value(NamespaceValueDef {
                            name: export.name.value(),
                            ts_type: format!("typeof {class_name}"),
                        }));
                    }
                    JsApiEntry::TypeAlias(_) => unreachable!(),
                }
            }
        }
        self.items.extend(
            namespaces
                .into_iter()
                .map(|(name, members)| Item::Namespace(NamespaceDef { name, members })),
        );
        Ok(())
    }
}

fn crate_root_file(src: &Path) -> Result<PathBuf, String> {
    if src.is_file() {
        return Ok(src.to_path_buf());
    }
    for name in ["lib.rs", "main.rs", "mod.rs"] {
        let candidate = src.join(name);
        if candidate.is_file() {
            return Ok(candidate);
        }
    }
    Err(format!(
        "no lib.rs, main.rs, or mod.rs under {}",
        src.display()
    ))
}

fn visit_file(
    file: &Path,
    module_dir: &Path,
    rust_module_path: &[String],
    visited: &mut HashSet<PathBuf>,
    extraction: &mut Extraction,
) -> Result<(), String> {
    let file = file
        .canonicalize()
        .map_err(|e| format!("resolve {}: {e}", file.display()))?;
    if !visited.insert(file.clone()) {
        return Ok(());
    }
    let text = std::fs::read_to_string(&file)
        .map_err(|e| format!("read Rust source {}: {e}", file.display()))?;
    let ast =
        syn::parse_file(&text).map_err(|e| format!("parse Rust source {}: {e}", file.display()))?;
    collect_items(
        &ast.items,
        &file,
        module_dir,
        rust_module_path,
        visited,
        extraction,
    )
}

fn collect_items(
    items: &[syn::Item],
    current_file: &Path,
    module_dir: &Path,
    rust_module_path: &[String],
    visited: &mut HashSet<PathBuf>,
    extraction: &mut Extraction,
) -> Result<(), String> {
    for item in items {
        match item {
            syn::Item::Impl(i) if !cfg_test(&i.attrs) => {
                if let Some(desc) = extract_impl(i).map_err(|error| {
                    format!("extract js_class in {}: {error}", current_file.display())
                })? {
                    extraction.items.push(desc);
                } else if has_attr(&i.attrs, "js_class") {
                    return Err(format!(
                        "could not extract #[js_class] impl in {}",
                        current_file.display()
                    ));
                } else if rong_typedef::has_orphan_js_methods(i) {
                    return Err(format!(
                        "#[js_method] appears in an impl without #[js_class] in {}",
                        current_file.display()
                    ));
                }
            }
            syn::Item::Struct(s) if !cfg_test(&s.attrs) => {
                if let Some(desc) = extract_struct(s).map_err(|error| {
                    format!("extract JS object in {}: {error}", current_file.display())
                })? {
                    extraction.items.push(desc);
                }
            }
            syn::Item::Enum(e) if !cfg_test(&e.attrs) => {
                if let Some(desc) = extract_numeric_enum(e).map_err(|error| {
                    format!(
                        "extract js_numeric_enum in {}: {error}",
                        current_file.display()
                    )
                })? {
                    extraction.items.push(desc);
                }
                if let Some(desc) = extract_union(e).map_err(|error| {
                    format!("extract js_union in {}: {error}", current_file.display())
                })? {
                    extraction.items.push(desc);
                }
            }
            syn::Item::Fn(function) if !cfg_test(&function.attrs) => {
                let key = qualified_item_name(rust_module_path, &function.sig.ident.to_string());
                extraction
                    .functions
                    .entry(key)
                    .or_default()
                    .push(function.clone());
            }
            syn::Item::Mod(m) if !cfg_test(&m.attrs) => {
                let child_dir = module_dir.join(m.ident.to_string());
                let mut child_module_path = rust_module_path.to_vec();
                child_module_path.push(m.ident.to_string());
                if let Some((_, inner)) = &m.content {
                    collect_items(
                        inner,
                        current_file,
                        &child_dir,
                        &child_module_path,
                        visited,
                        extraction,
                    )?;
                } else {
                    let path = resolve_module_file(m, current_file, module_dir)?;
                    let next_dir = if path.file_name().and_then(|n| n.to_str()) == Some("mod.rs") {
                        path.parent().unwrap_or(module_dir).to_path_buf()
                    } else {
                        path.with_extension("")
                    };
                    visit_file(&path, &next_dir, &child_module_path, visited, extraction)?;
                }
            }
            syn::Item::Macro(m) if path_last_is(&m.mac.path, "js_api") => {
                let api = syn::parse2::<JsApiInput>(m.mac.tokens.clone()).map_err(|e| {
                    format!(
                        "parse js_api! declaration in {}: {e}",
                        current_file.display()
                    )
                })?;
                extraction.apis.push((rust_module_path.to_vec(), api));
            }
            syn::Item::Macro(m) if macro_may_hide_js_api(m) => {
                return Err(format!(
                    "macro item in {} contains JS binding annotations; typegen cannot safely expand it",
                    current_file.display()
                ));
            }
            _ => {}
        }
    }
    Ok(())
}

fn qualified_item_name(module_path: &[String], item: &str) -> String {
    if module_path.is_empty() {
        item.to_string()
    } else {
        format!("{}::{item}", module_path.join("::"))
    }
}

fn resolve_function_key(
    functions: &BTreeMap<String, Vec<syn::ItemFn>>,
    module_path: &[String],
    path: &syn::Path,
) -> Result<String, String> {
    let mut segments: Vec<String> = path
        .segments
        .iter()
        .map(|segment| segment.ident.to_string())
        .collect();
    if segments.first().is_some_and(|segment| segment == "crate") {
        segments.remove(0);
    } else if segments.first().is_some_and(|segment| segment == "self") {
        segments.remove(0);
        let mut relative = module_path.to_vec();
        relative.extend(segments);
        let key = relative.join("::");
        return functions
            .contains_key(&key)
            .then_some(key)
            .ok_or_else(|| format!("cannot resolve namespace function `{}`", path_text(path)));
    } else if segments.first().is_some_and(|segment| segment == "super") {
        let mut relative = module_path.to_vec();
        while segments.first().is_some_and(|segment| segment == "super") {
            segments.remove(0);
            relative.pop().ok_or_else(|| {
                format!(
                    "namespace function path escapes crate: `{}`",
                    path_text(path)
                )
            })?;
        }
        relative.extend(segments);
        let key = relative.join("::");
        return functions
            .contains_key(&key)
            .then_some(key)
            .ok_or_else(|| format!("cannot resolve namespace function `{}`", path_text(path)));
    }

    let root_key = segments.join("::");
    if functions.contains_key(&root_key) {
        return Ok(root_key);
    }
    let mut relative = module_path.to_vec();
    relative.extend(segments);
    let relative_key = relative.join("::");
    functions
        .contains_key(&relative_key)
        .then_some(relative_key)
        .ok_or_else(|| format!("cannot resolve namespace function `{}`", path_text(path)))
}

fn path_text(path: &syn::Path) -> String {
    path.segments
        .iter()
        .map(|segment| segment.ident.to_string())
        .collect::<Vec<_>>()
        .join("::")
}

fn path_last_is(path: &syn::Path, name: &str) -> bool {
    path.segments
        .last()
        .is_some_and(|segment| segment.ident == name)
}

fn resolve_module_file(
    module: &syn::ItemMod,
    current_file: &Path,
    module_dir: &Path,
) -> Result<PathBuf, String> {
    if let Some(relative) = path_override(&module.attrs) {
        let base = current_file.parent().unwrap_or(module_dir);
        let path = base.join(relative);
        if path.is_file() {
            return Ok(path);
        }
        return Err(format!(
            "#[path] module file does not exist: {}",
            path.display()
        ));
    }

    let name = module.ident.to_string();
    let candidates = [
        module_dir.join(format!("{name}.rs")),
        module_dir.join(&name).join("mod.rs"),
    ];
    candidates
        .into_iter()
        .find(|path| path.is_file())
        .ok_or_else(|| {
            format!(
                "cannot resolve module `{name}` declared in {}",
                current_file.display()
            )
        })
}

fn path_override(attrs: &[syn::Attribute]) -> Option<PathBuf> {
    attrs.iter().find_map(|attr| {
        if !attr.path().is_ident("path") {
            return None;
        }
        let syn::Meta::NameValue(value) = &attr.meta else {
            return None;
        };
        let syn::Expr::Lit(expr) = &value.value else {
            return None;
        };
        let syn::Lit::Str(path) = &expr.lit else {
            return None;
        };
        Some(PathBuf::from(path.value()))
    })
}

fn cfg_test(attrs: &[syn::Attribute]) -> bool {
    attrs.iter().any(|attr| {
        if !attr.path().is_ident("cfg") {
            return false;
        }
        let syn::Meta::List(list) = &attr.meta else {
            return false;
        };
        list.parse_args::<syn::Meta>()
            .is_ok_and(|meta| matches!(meta, syn::Meta::Path(path) if path.is_ident("test")))
    })
}

fn has_attr(attrs: &[syn::Attribute], name: &str) -> bool {
    attrs.iter().any(|attr| {
        attr.path()
            .segments
            .last()
            .is_some_and(|segment| segment.ident == name)
    })
}

fn macro_may_hide_js_api(item: &syn::ItemMacro) -> bool {
    let tokens = item.mac.tokens.to_string();
    [
        "js_class",
        "js_method",
        "js_numeric_enum",
        "js_union",
        "FromJSObject",
        "IntoJSObject",
    ]
    .iter()
    .any(|needle| tokens.contains(needle))
}

fn sort_key(item: &Item) -> String {
    match item {
        Item::TypeAlias(alias) => format!("0:{}", alias.name),
        Item::Interface(i) => format!("1:{}", i.name),
        Item::NumericEnum(e) => format!("2:{}", e.name),
        Item::Class(c) => format!("3:{}", c.name),
        Item::Namespace(namespace) => format!("4:{}", namespace.name),
    }
}

fn header(module: &str) -> String {
    format!(
        "// Generated by rong-typegen from the {module} module's Rust source.\n\
         // Do not edit by hand — run `cargo run -p rong_typegen` to regenerate.\n\n"
    )
}

fn format_paths(message: &str, paths: &[PathBuf]) -> String {
    let paths = paths
        .iter()
        .map(|path| format!("\n  {}", path.display()))
        .collect::<String>();
    format!("{message}:{paths}")
}

fn dir_name(p: &Path) -> String {
    let base = if p.file_name().and_then(|n| n.to_str()) == Some("src") {
        p.parent().unwrap_or(p)
    } else {
        p
    };
    base.file_name()
        .and_then(|n| n.to_str())
        .map(|n| n.strip_prefix("rong_").unwrap_or(n).to_string())
        .unwrap_or_else(|| "module".to_string())
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("repo root")
        .to_path_buf()
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::time::{SystemTime, UNIX_EPOCH};

    fn args(a: &[&str]) -> Vec<String> {
        a.iter().map(|s| s.to_string()).collect()
    }

    #[test]
    fn cli_args_are_strict_and_support_downstream_config() {
        assert_eq!(
            CliArgs::parse(&args(&["--check", "--config", "types.json"])).unwrap(),
            CliArgs {
                check: true,
                config: Some("types.json".into()),
                ..Default::default()
            }
        );
        assert!(CliArgs::parse(&args(&["--unknown"])).is_err());
        assert!(CliArgs::parse(&args(&["--config"])).is_err());
        assert!(CliArgs::parse(&args(&["--config", "a.json", "--out", "generated"])).is_err());
        assert!(CliArgs::parse(&args(&["src"])).is_err());
    }

    #[test]
    fn dir_name_strips_src_and_rong_prefix() {
        assert_eq!(dir_name(Path::new("/a/lingxia-logic/src")), "lingxia-logic");
        assert_eq!(dir_name(Path::new("/a/rong_sqlite")), "sqlite");
    }

    #[test]
    fn cfg_test_is_excluded_but_other_cfgs_are_target_agnostic() {
        let test: syn::ItemMod = syn::parse_quote! { #[cfg(test)] mod tests {} };
        let unix: syn::ItemMod = syn::parse_quote! { #[cfg(unix)] mod unix {} };
        assert!(cfg_test(&test.attrs));
        assert!(!cfg_test(&unix.attrs));
    }

    #[test]
    fn module_graph_ignores_unreferenced_files_and_test_modules() {
        let root = temp_dir("module-graph");
        let src = root.join("src");
        std::fs::create_dir_all(&src).unwrap();
        std::fs::write(
            src.join("lib.rs"),
            "mod live;\n#[cfg(test)] mod tests { #[derive(FromJSObject)] struct TestOnly { value: String } }\n",
        )
        .unwrap();
        std::fs::write(
            src.join("live.rs"),
            "#[derive(FromJSObject)] struct Live { value: String }\n",
        )
        .unwrap();
        std::fs::write(
            src.join("dead.rs"),
            "#[derive(FromJSObject)] struct Dead { value: String }\n",
        )
        .unwrap();

        let module = module_from_crate(&CrateSrc {
            name: "fixture".into(),
            src,
        })
        .unwrap();
        let names: Vec<_> = module
            .items
            .iter()
            .map(|item| match item {
                Item::Interface(value) => value.name.as_str(),
                _ => "unexpected",
            })
            .collect();
        assert_eq!(names, ["Live"]);
        std::fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn managed_outputs_are_explicitly_enumerated() {
        let root = temp_dir("managed-outputs");
        let src = root.join("src");
        let generated = root.join("generated");
        std::fs::create_dir_all(&src).unwrap();
        std::fs::create_dir_all(&generated).unwrap();
        std::fs::write(src.join("canonical.ts"), format!("{GEN_MARKER}\n")).unwrap();
        std::fs::write(src.join("hand.ts"), "export interface Hand {}\n").unwrap();
        std::fs::write(generated.join("stale.ts"), format!("{GEN_MARKER}\n")).unwrap();

        let managed = managed_outputs(&root).unwrap();
        assert!(managed.contains(&src.join("canonical.ts")));
        assert!(managed.contains(&generated.join("stale.ts")));
        assert!(!managed.contains(&src.join("hand.ts")));
        std::fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn js_api_resolves_function_signatures_and_type_aliases() {
        let root = temp_dir("js-api");
        let src = root.join("src");
        std::fs::create_dir_all(&src).unwrap();
        std::fs::write(
            src.join("lib.rs"),
            "mod api;\njs_api! { fn register(ctx) { namespace RongNamespace = ctx.host_namespace(); type Name = \"string\"; fn ping = api::ping; } }\n",
        )
        .unwrap();
        std::fs::write(
            src.join("api.rs"),
            "/// Ping a name.\npub(crate) async fn ping(name: String) -> JSResult<String> { todo!() }\n",
        )
        .unwrap();

        let module = module_from_crate(&CrateSrc {
            name: "fixture".into(),
            src,
        })
        .unwrap();
        let namespace = module
            .items
            .iter()
            .find_map(|item| match item {
                Item::Namespace(namespace) => Some(namespace),
                _ => None,
            })
            .unwrap();
        let NamespaceMember::Function(function) = &namespace.members[0] else {
            panic!("function")
        };
        assert_eq!(function.name, "ping");
        assert_eq!(function.sig.params[0].ts_type, "string");
        assert_eq!(function.sig.ret, "Promise<string>");
        assert_eq!(function.docs, ["Ping a name."]);
        let alias = module
            .items
            .iter()
            .find_map(|item| match item {
                Item::TypeAlias(alias) => Some(alias),
                _ => None,
            })
            .unwrap();
        assert_eq!(alias.name, "Name");
        assert_eq!(alias.ts_type, "string");
        std::fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn downstream_config_generates_an_independent_logic_surface_and_profile() {
        let root = temp_dir("downstream-logic");
        let crate_src = root.join("crates/logic/src");
        let types = root.join("packages/types");
        std::fs::create_dir_all(&crate_src).unwrap();
        std::fs::create_dir_all(&types).unwrap();
        std::fs::write(
            crate_src.join("lib.rs"),
            r#"
                #[derive(IntoJSObject)]
                struct DeviceInfo { platform: String }

                fn get_device_info() -> JSResult<DeviceInfo> { todo!() }

                rong::js_api! {
                    fn register_logic(ctx) {
                        namespace Lx = lx::namespace(ctx);
                        fn getDeviceInfo = get_device_info;
                    }
                }
            "#,
        )
        .unwrap();
        let config = types.join("typegen.json");
        std::fs::write(
            &config,
            r#"{
                "source": "../../crates/logic/src",
                "name": "logic",
                "out": "src/generated/logic.ts",
                "global_objects": { "lx": "Lx" },
                "profiles": { "logic-web": "src/logic-globals.d.ts" }
            }"#,
        )
        .unwrap();

        run_downstream_config(&config, false).unwrap();
        let logic = std::fs::read_to_string(types.join("src/generated/logic.ts")).unwrap();
        assert!(logic.contains("export interface DeviceInfo"));
        assert!(logic.contains("export interface Lx"));
        assert!(logic.contains("getDeviceInfo(): DeviceInfo"));
        assert!(logic.contains("const lx: Lx"));

        let profile = std::fs::read_to_string(types.join("src/logic-globals.d.ts")).unwrap();
        assert!(profile.contains("declare function fetch"));
        assert!(!profile.contains("interface Document"));
        std::fs::remove_dir_all(root).unwrap();
    }

    #[test]
    fn logic_web_profile_is_dom_free_and_contains_runtime_fetch() {
        let profile = runtime_profile(RuntimeProfile::LogicWeb);
        assert!(profile.contains("declare function fetch"));
        assert!(profile.contains("interface Request"));
        assert!(profile.contains("declare var CompressionStream"));
        assert!(!profile.contains("interface Document"));
        assert!(!profile.contains("declare var window"));
    }

    fn temp_dir(label: &str) -> PathBuf {
        let nonce = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .unwrap()
            .as_nanos();
        std::env::temp_dir().join(format!(
            "rong-typegen-{label}-{}-{nonce}",
            std::process::id()
        ))
    }
}
