//! Generate TypeScript definitions for RongJS modules from their Rust source.
//!
//! Parses each crate's `.rs` files with `syn`, extracts `#[js_class]` /
//! `FromJSObj` / `IntoJSObj` descriptors, and renders one `.ts` per module.
//! No compilation, no runtime — it only reads source, so it is fast and works
//! on any crate that uses the `#[js_*]` macros (rong's modules or a downstream
//! crate like `lingxia-logic`).
//!
//! Usage:
//!   cargo run -p rong_typegen                 # regenerate rong's module types
//!   cargo run -p rong_typegen -- --check      # CI drift-guard (no writes)
//!   cargo run -p rong_typegen -- --out DIR --name NAME SRC_DIR
//!                                             # generate one crate's types

use rong_typedef::model::{Item, ModuleTypeDef};
use rong_typedef::{extract_const_enum, extract_impl, extract_struct, render_module};
use std::path::{Path, PathBuf};
use std::process::ExitCode;

/// Marker at the top of every generated file. A `src/<module>.ts` that starts
/// with it is "canonical" (published straight from generation); one that does
/// not is hand-authored, and generation for it lands in `generated/` as a
/// drift reference instead.
const GEN_MARKER: &str = "// Generated by rong-typegen";

fn main() -> ExitCode {
    let args: Vec<String> = std::env::args().skip(1).collect();
    let check = args.iter().any(|a| a == "--check");
    let explicit_out = flag(&args, "--out").map(PathBuf::from);

    // Explicit single-crate mode, or default: every rong module crate.
    let crates: Vec<CrateSrc> = match positional(&args) {
        Some(src) => vec![CrateSrc {
            name: flag(&args, "--name").unwrap_or_else(|| dir_name(&PathBuf::from(&src))),
            src: PathBuf::from(src),
        }],
        None => rong_module_crates(),
    };

    let mut modules: Vec<ModuleTypeDef> = crates
        .iter()
        .map(module_from_crate)
        .filter(|m| !m.items.is_empty())
        .collect();
    modules.sort_by(|a, b| a.module.cmp(&b.module));

    if modules.is_empty() {
        eprintln!("error: no JS-facing types found — check the source paths.");
        return ExitCode::FAILURE;
    }

    let pkg = repo_root().join("packages/rong_types");
    // Irreducible TS with no Rust origin lives in `preludes/<module>.ts`.
    let prelude_dir = match &explicit_out {
        Some(out) => out.parent().map(|p| p.join("preludes")),
        None => Some(pkg.join("preludes")),
    };

    let mut stale = Vec::new();
    for module in &modules {
        let prelude = prelude_dir
            .as_ref()
            .map(|d| d.join(format!("{}.ts", module.module)))
            .and_then(|p| std::fs::read_to_string(p).ok())
            .map(|s| format!("{}\n\n", s.trim_end()))
            .unwrap_or_default();
        let rendered = header(&module.module) + &prelude + &render_module(module);

        let file = match &explicit_out {
            Some(out) => out.join(format!("{}.ts", module.module)),
            None => target_file(&pkg, &module.module),
        };

        if check {
            if std::fs::read_to_string(&file).unwrap_or_default() != rendered {
                stale.push(file.display().to_string());
            }
        } else {
            if let Some(parent) = file.parent()
                && let Err(e) = std::fs::create_dir_all(parent)
            {
                eprintln!("error: create dir {}: {e}", parent.display());
                return ExitCode::FAILURE;
            }
            if let Err(e) = std::fs::write(&file, &rendered) {
                eprintln!("error: write {}: {e}", file.display());
                return ExitCode::FAILURE;
            }
            println!("generated {}", file.display());
        }
    }

    if check {
        if stale.is_empty() {
            println!("types are up to date ({} modules).", modules.len());
        } else {
            eprintln!("error: generated types are out of date:");
            for f in &stale {
                eprintln!("  {f}");
            }
            eprintln!("run `cargo run -p rong_typegen` to update them.");
            return ExitCode::FAILURE;
        }
    }
    ExitCode::SUCCESS
}

/// Where a module's output belongs: `src/<module>.ts` when that file is already
/// canonical (starts with [`GEN_MARKER`]), else the `generated/` reference.
fn target_file(pkg: &Path, module: &str) -> PathBuf {
    let src = pkg.join("src").join(format!("{module}.ts"));
    let canonical = std::fs::read_to_string(&src)
        .map(|s| s.starts_with(GEN_MARKER))
        .unwrap_or(false);
    if canonical {
        src
    } else {
        pkg.join("generated").join(format!("{module}.ts"))
    }
}

struct CrateSrc {
    /// Short module name used for the output file (e.g. `sqlite`).
    name: String,
    /// Directory to scan recursively for `.rs` files.
    src: PathBuf,
}

/// Discover rong's module crates: `modules/rong_*/src`.
fn rong_module_crates() -> Vec<CrateSrc> {
    let modules = repo_root().join("modules");
    let mut out = Vec::new();
    if let Ok(entries) = std::fs::read_dir(&modules) {
        for entry in entries.flatten() {
            let dir = entry.path();
            let src = dir.join("src");
            if src.is_dir()
                && let Some(name) = dir.file_name().and_then(|n| n.to_str())
            {
                out.push(CrateSrc {
                    name: name.strip_prefix("rong_").unwrap_or(name).to_string(),
                    src,
                });
            }
        }
    }
    out
}

/// Parse every `.rs` file under a crate's src and collect its descriptors.
fn module_from_crate(c: &CrateSrc) -> ModuleTypeDef {
    let mut items = Vec::new();
    for file in rs_files(&c.src) {
        let Ok(text) = std::fs::read_to_string(&file) else {
            continue;
        };
        let Ok(ast) = syn::parse_file(&text) else {
            eprintln!("warning: could not parse {}", file.display());
            continue;
        };
        collect_items(&ast.items, &mut items);
    }
    items.sort_by_key(sort_key);
    ModuleTypeDef {
        module: c.name.clone(),
        items,
    }
}

/// Walk items (recursing into inline `mod`s) and extract descriptors.
fn collect_items(items: &[syn::Item], out: &mut Vec<Item>) {
    for item in items {
        match item {
            syn::Item::Impl(i) => {
                if let Some(desc) = extract_impl(i) {
                    out.push(desc);
                } else if rong_typedef::has_orphan_js_methods(i) {
                    eprintln!(
                        "warning: `#[js_method]` in an impl without `#[js_class]` — those methods are not generated"
                    );
                }
            }
            syn::Item::Struct(s) => {
                if let Some(desc) = extract_struct(s) {
                    out.push(desc);
                }
            }
            syn::Item::Enum(e) => {
                if let Some(desc) = extract_const_enum(e) {
                    out.push(desc);
                }
            }
            syn::Item::Mod(m) => {
                if let Some((_, inner)) = &m.content {
                    collect_items(inner, out);
                }
            }
            _ => {}
        }
    }
}

/// Order: type aliases, then interfaces, then classes; alphabetical within.
fn sort_key(item: &Item) -> String {
    match item {
        Item::TypeAlias(a) => format!("0:{}", a.name),
        Item::Interface(i) => format!("1:{}", i.name),
        Item::ConstEnum(e) => format!("2:{}", e.name),
        Item::Class(c) => format!("3:{}", c.name),
    }
}

fn rs_files(dir: &Path) -> Vec<PathBuf> {
    let mut out = Vec::new();
    let mut stack = vec![dir.to_path_buf()];
    while let Some(d) = stack.pop() {
        let Ok(entries) = std::fs::read_dir(&d) else {
            continue;
        };
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() {
                stack.push(path);
            } else if path.extension().and_then(|e| e.to_str()) == Some("rs") {
                out.push(path);
            }
        }
    }
    out.sort();
    out
}

fn header(module: &str) -> String {
    format!(
        "// Generated by rong-typegen from the {module} module's Rust source.\n\
         // Do not edit by hand — run `cargo run -p rong_typegen` to regenerate.\n\n"
    )
}

fn flag(args: &[String], name: &str) -> Option<String> {
    let idx = args.iter().position(|a| a == name)?;
    args.get(idx + 1).cloned()
}

/// The first non-flag, non-flag-value argument (the source dir in single mode).
fn positional(args: &[String]) -> Option<String> {
    let mut i = 0;
    while i < args.len() {
        let a = &args[i];
        if a == "--check" {
            i += 1;
        } else if a == "--out" || a == "--name" {
            i += 2; // skip flag + its value
        } else {
            return Some(a.clone());
        }
    }
    None
}

fn dir_name(p: &Path) -> String {
    // `.../lingxia-logic/src` -> `lingxia-logic`
    let base = if p.file_name().and_then(|n| n.to_str()) == Some("src") {
        p.parent().unwrap_or(p)
    } else {
        p
    };
    base.file_name()
        .and_then(|n| n.to_str())
        .map(|n| n.strip_prefix("rong_").unwrap_or(n).to_string())
        .unwrap_or_else(|| "module".to_string())
}

fn repo_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("repo root")
        .to_path_buf()
}

#[cfg(test)]
mod tests {
    use super::*;

    fn args(a: &[&str]) -> Vec<String> {
        a.iter().map(|s| s.to_string()).collect()
    }

    #[test]
    fn flag_reads_value_after_name() {
        let a = args(&["--out", "dir", "--name", "x"]);
        assert_eq!(flag(&a, "--out").as_deref(), Some("dir"));
        assert_eq!(flag(&a, "--name").as_deref(), Some("x"));
        assert_eq!(flag(&a, "--missing"), None);
    }

    #[test]
    fn positional_skips_flags_and_their_values() {
        assert_eq!(
            positional(&args(&["--check", "--out", "gen", "src/path"])).as_deref(),
            Some("src/path")
        );
        assert_eq!(positional(&args(&["--check"])), None);
    }

    #[test]
    fn dir_name_strips_src_and_rong_prefix() {
        assert_eq!(dir_name(Path::new("/a/lingxia-logic/src")), "lingxia-logic");
        assert_eq!(dir_name(Path::new("/a/rong_sqlite")), "sqlite");
    }
}
